name: nba_rookie
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.24.3
  - seaborn=0.12.2
  - pandas=1.5.1
  - ipykernel=6.25.0
  - pip:
    - scikit-learn==0.24.0
    - auto-sklearn==0.15.0
    - mlserver==1.3.5
    - mlserver-sklearn==1.3.5
    - matplotlib==3.6.3
    - requests==2.31.0
